export const API_ERROR = 'API_ERROR_RECEIVED';
export const WEATHER_DATA_RECEIVED = 'WEATHER_DATA_RECEIVED';
export const METRIC_DATA_RECEIVED = 'METRIC_DATA_RECEIVED';
export const LAST_METRIC_MEASUREMENT = 'LAST_METRIC_MEASUREMENT';
export const SELECT_LIST_METRICS = 'SELECT_LIST_METRICS';
export const DEFINE_LIST_METRICS = 'DEFINE_LIST_METRICS';
